# Generated by Django 4.2.7 on 2023-12-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_diseases_dashboardname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
