# Generated by Django 4.2.7 on 2023-12-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_user_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseases',
            name='precautions',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseases',
            name='symptoms',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
