# Generated by Django 4.2.7 on 2023-12-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_diseases_precautions_diseases_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='slug',
            field=models.TextField(max_length=130),
        ),
    ]
