# Generated by Django 4.2.7 on 2023-12-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_diseases_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseases',
            name='imageLink',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
    ]
