# Generated by Django 4.2.7 on 2023-12-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_diseases_imagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='imageLink',
            field=models.ImageField(max_length=130, upload_to=''),
        ),
    ]
