# Generated by Django 4.2.7 on 2023-12-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_diseases_imagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='imageLink',
            field=models.ImageField(upload_to='static'),
        ),
    ]
