# Generated by Django 4.2.7 on 2024-01-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_diseases_imagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseases',
            name='image2Link',
            field=models.ImageField(default='', upload_to='static'),
            preserve_default=False,
        ),
    ]
